### ISSUE TITLE
landing with campaigns (posts, 2 sections intro, campaign)

### ISSUE THREAD

**Issue by roncheok** [squarrific/ordinary-website#1]

**Comment by zihaolam** [comment]
landing page 2 sections intro - 
![image](https://user-images.githubusercontent.com/22425816/78228707-a3199000-7501-11ea-97da-d4c4aec1435b.png)

campaigns - 
![image](https://user-images.githubusercontent.com/22425816/78228778-b75d8d00-7501-11ea-994e-59f3a7a3d602.png)
