### ISSUE TITLE
Accounts CRUD index/show/edit/new

### ISSUE THREAD

**Issue by roncheok** [squarrific/ordinary-website#6]

**Comment by dafuallah96** [comment]
accounts/index

![Screenshot 2020-03-25 at 5 48 09 PM](https://user-images.githubusercontent.com/32087554/77523626-fc117480-6ec0-11ea-8e1f-4f80f2135b4e.png)

accounts/new

![Screenshot 2020-03-25 at 5 48 27 PM](https://user-images.githubusercontent.com/32087554/77523659-0895cd00-6ec1-11ea-906c-057ad11ede3f.png)

accounts/edit

![Screenshot 2020-03-25 at 5 48 16 PM](https://user-images.githubusercontent.com/32087554/77523686-10557180-6ec1-11ea-9ac0-16bd0a5e2561.png)
