### ISSUE TITLE
Campaigns CRUD index/show/edit/new (which is posts, must have account)

### ISSUE THREAD

**Issue by roncheok** [squarrific/ordinary-website#7]

**Comment by dafuallah96** [comment]
View
Link: https://www.ordinary.im/profile/posts
![Screenshot 2020-04-03 at 2 07 30 AM](https://user-images.githubusercontent.com/32087554/78283088-e1d63700-754f-11ea-8305-aebb00ad6513.png)

Add
Link: https://www.ordinary.im/profile/posts/new
![Screenshot 2020-04-03 at 2 08 13 AM](https://user-images.githubusercontent.com/32087554/78283157-fc101500-754f-11ea-8748-6e6c891d1587.png)

Edit
Link: https://www.ordinary.im/profile/posts/40280/edit
![Screenshot 2020-04-03 at 2 09 12 AM](https://user-images.githubusercontent.com/32087554/78283271-1f3ac480-7550-11ea-89b3-efe29cee2d7b.png)
